In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4, 5, 6]

In [3]:
a = np.asarray(l)

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a)

[1 2 3 4 5 6]


In [6]:
import numpy as np

In [7]:
l = [1, 2, 3, 4, 5, 6, 7]

In [8]:
a = np.asarray(l)

In [9]:
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [10]:
import numpy as np

In [11]:
l = [[1, 2, 3, 4, 5, 6, 7], [8, 9]]

In [14]:
a = np.asarray(l)

C:\Users\Sheeraz\anaconda3\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


In [15]:
print(type(a))
print(a)

<class 'numpy.ndarray'>
[list([1, 2, 3, 4, 5, 6, 7]) list([8, 9])]


In [16]:
import numpy as np

In [21]:
l = b"Hello Word"

In [22]:
print(type(l))

<class 'bytes'>


In [23]:
a = np.frombuffer(l, dtype = "S1")

In [24]:
print(type(a))

<class 'numpy.ndarray'>


In [25]:
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'd']


In [26]:
import numpy as np

In [27]:
lst = [0, 2, 4, 6]

In [28]:
it = iter(lst)

In [30]:
x = np.fromiter(it, dtype = float)

In [34]:
print(x)

[0. 2. 4. 6.]


In [33]:
print(type(x))

<class 'numpy.ndarray'>
