In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]])

In [3]:
print("Printing array")

Printing array


In [4]:
print(a)

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]


In [5]:
print("itering over the array")

itering over the array


In [6]:
for x in np.nditer(a):
    print(x, end=" ")

1 2 3 4 2 4 5 6 10 20 39 3 

In [7]:
import numpy as np

In [15]:
a = np.array([[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]])

In [16]:
print("Print the array:")
print(a)

Print the array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]


In [20]:
print("Printing the transport of the array")
at = a.T
print(at)

for x in np.nditer(at):
    print("itering over the array")
    print(x)

for x in np.nditer(a):
    print(x, end=" ")    

Printing the transport of the array
[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
itering over the array
1
itering over the array
2
itering over the array
3
itering over the array
4
itering over the array
2
itering over the array
4
itering over the array
5
itering over the array
6
itering over the array
10
itering over the array
20
itering over the array
39
itering over the array
3
1 2 3 4 2 4 5 6 10 20 39 3 

In [21]:
import numpy as np

In [22]:
a = np.array([[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]])

In [25]:
print("\nPrinting the array:\n")

print(a)

print("\nPrinting the transport of the array")

at = a.T

print(at)

print("\nIterating over the transported array\n")

for x in np.nditer(at):
    print(x, end=" ")

print("\nSorting the transported array in C-style:\n")

c = at.copy(order = "C")
print(c)

print("\nIterating over the C-style array:\n")

for x in np.nditer(c):
    print(x, end=" ")
    
d = at.copy(order="F")

print(d)

print("Iterating over the F-style array:\n")

for x in np.nditer(d):
    print(x, end=" ")


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transport of the array
[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transported array

1 2 3 4 2 4 5 6 10 20 39 3 
Sorting the transported array in C-style:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 [[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
Iterating over the F-style array:

1 2 3 4 2 4 5 6 10 20 39 3 

In [27]:
import numpy as np

In [28]:
a = np.array([[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]])

In [29]:
print("\nPrinting the array:\n")

print(a)

print("\nPrinting the transpose of the array:\n")

at = a.T

print(at)

print("\nIterating over the transposed array\n")

for x in np.nditer(at):
    print(x, end=" ")
    
print("\nSorting the transposed array in C-style:\n")

print("nIterating over the C-style array:\n")

for x in np.nditer(at, order= "C"):
    print(x, end=" ")


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Sorting the transposed array in C-style:

nIterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 

In [30]:
import numpy as np

a = np.array([[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]])

print("\nPrinting the original array:\n")

print(a)

print("\nIterating over the modified array\n")

for x in np.nditer(a, op_flags=["readwrite"]):
    x[...] = 3 * x
    
    print(x, end=" ")


Printing the original array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Iterating over the modified array

3 6 9 12 6 12 15 18 30 60 117 9 