In [1]:
import numpy as np

In [2]:
a = np.array

In [3]:
print(a)

<built-in function array>


In [4]:
import numpy

In [5]:
a = numpy.array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
import numpy

In [9]:
a = numpy.array([[1, 2, 3], [4, 5, 6]])

In [10]:
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy

In [12]:
a = numpy.array([1, 3, 7, 12], dtype=complex)

In [13]:
print(a)

[ 1.+0.j  3.+0.j  7.+0.j 12.+0.j]


In [14]:
import numpy as np

In [15]:
arr = np.array([[1, 2, 3, 12], [4, 5, 6, 13], [7, 8, 2, 15]])

In [16]:
print(arr.ndim)

2


In [17]:
print(arr)

[[ 1  2  3 12]
 [ 4  5  6 13]
 [ 7  8  2 15]]


In [18]:
import numpy as np

In [19]:
a = np.array([[1, 2, 3]])

In [20]:
print("Each Item Contains", a.itemsize, "Bytes")

Each Item Contains 4 Bytes


In [21]:
import numpy as np

In [22]:
a = np.array([[1, 2, 3]])

In [24]:
print("Each Item is of the Type", a.dtype)

Each Item is of the Type int32


In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7]])

In [3]:
print("Size: ", a.size)

Size:  7


In [5]:
print("Shape: ", a.shape)

Shape:  (1, 7)


In [6]:
import numpy as np

In [7]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [9]:
print("Printing the Original Array")

Printing the Original Array


In [10]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
a = a.reshape(2, 3)

In [12]:
print("printing the Reshaping the Array")

printing the Reshaping the Array


In [13]:
print(a)

[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np

In [15]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [16]:
print(a[0, 1])

2


In [17]:
print(a[2, 0])

5


In [18]:
import numpy as np

In [19]:
#prints 10 values which are evenly spaced over the given interval 5-15
a = np.linspace(5, 15, 10)

In [20]:
print(a)

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [21]:
import numpy as np

In [22]:
a = np.array([1, 2, 3, 10, 15, 4])

In [24]:
print("The Array:", a)

The Array: [ 1  2  3 10 15  4]


In [25]:
print("The Minimum Element:", a.min())

The Minimum Element: 1


In [26]:
print("The Maximum Element:", a.max())

The Maximum Element: 15


In [28]:
print("the Sum of the Elements:", a.sum())

the Sum of the Elements: 35


In [29]:
import numpy as np

In [30]:
a = np.array([[1, 2, 30], [10, 15, 4]])

In [31]:
print("The Array:", a)

The Array: [[ 1  2 30]
 [10 15  4]]


In [33]:
print("The Maximum Elements of Columns:", a.max(axis = 0))

The Maximum Elements of Columns: [10 15 30]


In [34]:
print("The Minimum Element of Rows:", a.min(axis = 1))

The Minimum Element of Rows: [1 4]


In [35]:
print("Sum of All Rows:", a.sum(axis = 1))

Sum of All Rows: [33 29]


In [36]:
import numpy as np

In [37]:
a = np.array([[1, 2, 30], [10, 15, 4]])

In [38]:
print(np.sqrt(a))

[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]


In [39]:
print(np.std(a))

10.044346115546242


In [40]:
import numpy as np

In [43]:
a = np.array([[1, 2, 30], [10, 15, 4]])

In [44]:
b = np.array([[1, 2, 3], [12, 19, 2]])

In [45]:
print("Sum of Array a and b\n", a + b)

Sum of Array a and b
 [[ 2  4 33]
 [22 34  6]]


In [46]:
print("Sub of Array a and b\n", a - b)

Sub of Array a and b
 [[ 0  0 27]
 [-2 -4  2]]


In [47]:
print("Product of Array a and b\n", a * b)

Product of Array a and b
 [[  1   4  90]
 [120 285   8]]


In [48]:
print("Division of Array a and b\n", a / b)

Division of Array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  2.        ]]


In [49]:
import numpy as np

In [50]:
a = np.array([[1, 2, 30], [10, 15, 4]])

In [51]:
b = np.array([[1, 2, 3], [12, 19, 29]])

In [52]:
print("Array Vertically Concatented\n", np.vstack((a, b)))

Array Vertically Concatented
 [[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]


In [53]:
print("Array Horizontally Concatentend\n", np.hstack((a, b)))

Array Horizontally Concatentend
 [[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]
