In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [6]:
b = np.array([2, 4, 6, 8, 10, 12, 14])

In [7]:
c = a * b

In [8]:
print(c)

[ 2  8 18 32 50 72 98]


In [9]:
import numpy as np

In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [11]:
b = np.array([2, 4, 6, 8, 10, 12, 14, 19])

In [13]:
c = a * b
print(c)

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [14]:
import numpy as np

In [15]:
a = np.array([[1, 2, 3, 4], [2, 4, 5, 6], [10, 20, 39, 3]])

In [16]:
b = np.array([2, 4, 6, 8])

In [19]:
print("printing array a..")
print(a)

printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]


In [21]:
print("printing array b..")
print(b)

printing array b..
[2 4 6 8]


In [22]:
print("adding array a and b..")
c = a + b
print(c)

adding array a and b..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [23]:
print("printing array a..")
print(a)

print("\nprinting array b..")
print(b)

print("\nadding array a and b..")
c = a + b
print(c)

printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

adding array a and b..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]
