In [1]:
import numpy as np

In [2]:
arr = np.empty((3, 2), dtype = int)

In [3]:
print(arr)

[[-2062766688         580]
 [          0           0]
 [     131074  1681093221]]


In [4]:
import numpy as np

In [5]:
arr = np.zeros((2, 3), dtype = int)

In [6]:
print(arr)

[[0 0 0]
 [0 0 0]]


In [7]:
import numpy as np

In [8]:
arr = np.ones((3, 2), dtype = int)

In [9]:
print(arr)

[[1 1]
 [1 1]
 [1 1]]
