In [1]:
import numpy as np

In [3]:
arr = np.array([0, 30, 60, 90, 120, 150, 180])

print("\nThe sin value of the angles", end=" ")

print(np.sin(arr * np.pi / 180))

print("\nThe cosine value of the angles", end=" ")

print(np.cos(arr * np.pi / 180))

print("\nThe tangent value of the angles", end=" ")

print(np.tan(arr * np.pi / 180))


The sin value of the angles [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

The cosine value of the angles [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

The tangent value of the angles [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [4]:
import numpy as np

arr = np.array([0, 30, 60, 90])

print("printing the sin values of different angles")

sinval = np.sin(np.pi / 180)

print(sinval)

print("printing the inverse of the sin")

cosec = np.arcsin(sinval)

print(cosec)

print("printing the values in degrees")

print(np.degrees(cosec))

print("\nprinting the cos values of different angles")

cosval = np.cos(arr * np.pi / 180)

print(cosval)

print("printing the inverse of the cos")

sec = np.arccos(cosval)

print(sec)

print("\nprinting the values in degrees")

print(np.degrees(sec))

print("\nprinting the tan values of different angles")

tanval = np.tan(arr * np.pi / 180)

print(tanval)

print("printing the inverse of the tan")

cot = np.arctan(tanval)

print(cot)

print("\nprinting the values in degrees")

print(np.degrees(cot))

printing the sin values of different angles
0.01745240643728351
printing the inverse of the sin
0.017453292519943295
printing the values in degrees
1.0

printing the cos values of different angles
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
printing the inverse of the cos
[0.         0.52359878 1.04719755 1.57079633]

printing the values in degrees
[ 0. 30. 60. 90.]

printing the tan values of different angles
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]
printing the inverse of the tan
[0.         0.52359878 1.04719755 1.57079633]

printing the values in degrees
[ 0. 30. 60. 90.]


In [5]:
import numpy as np

In [6]:
arr = np.array([12.202, 90.23120, 123.020, 23.202])

print("printing the original array values:", end=" ")

print(arr)

print("Array values rounded off to 2 decimal position", np.around(arr, 2))

print("Array values rounded off to -1 decimal position", np.around(arr, -1))

printing the original array values: [ 12.202   90.2312 123.02    23.202 ]
Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


In [7]:
import numpy as np

arr = np.array([12.202, 90.23120, 123.020, 23.202])

print(np.floor(arr))

[ 12.  90. 123.  23.]


In [8]:
import numpy as np

arr = np.array([12.202, 90.23120, 123.020, 23.202])

print(np.ceil(arr))

[ 13.  91. 124.  24.]
